/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TkMilesRouteImport } from './routes/tk-miles'
import { Route as MyTripsRouteImport } from './routes/my-trips'
import { Route as ManageBookingRouteImport } from './routes/manage-booking'
import { Route as FlightStatusRouteImport } from './routes/flight-status'
import { Route as DestinationsRouteImport } from './routes/destinations'
import { Route as CheckInRouteImport } from './routes/check-in'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AdminMessagesRouteImport } from './routes/admin.messages'

const TkMilesRoute = TkMilesRouteImport.update({
  id: '/tk-miles',
  path: '/tk-miles',
  getParentRoute: () => rootRouteImport,
} as any)
const MyTripsRoute = MyTripsRouteImport.update({
  id: '/my-trips',
  path: '/my-trips',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageBookingRoute = ManageBookingRouteImport.update({
  id: '/manage-booking',
  path: '/manage-booking',
  getParentRoute: () => rootRouteImport,
} as any)
const FlightStatusRoute = FlightStatusRouteImport.update({
  id: '/flight-status',
  path: '/flight-status',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsRoute = DestinationsRouteImport.update({
  id: '/destinations',
  path: '/destinations',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckInRoute = CheckInRouteImport.update({
  id: '/check-in',
  path: '/check-in',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/admin/messages',
  path: '/admin/messages',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/check-in': typeof CheckInRoute
  '/destinations': typeof DestinationsRoute
  '/flight-status': typeof FlightStatusRoute
  '/manage-booking': typeof ManageBookingRoute
  '/my-trips': typeof MyTripsRoute
  '/tk-miles': typeof TkMilesRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/check-in': typeof CheckInRoute
  '/destinations': typeof DestinationsRoute
  '/flight-status': typeof FlightStatusRoute
  '/manage-booking': typeof ManageBookingRoute
  '/my-trips': typeof MyTripsRoute
  '/tk-miles': typeof TkMilesRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/check-in': typeof CheckInRoute
  '/destinations': typeof DestinationsRoute
  '/flight-status': typeof FlightStatusRoute
  '/manage-booking': typeof ManageBookingRoute
  '/my-trips': typeof MyTripsRoute
  '/tk-miles': typeof TkMilesRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/check-in'
    | '/destinations'
    | '/flight-status'
    | '/manage-booking'
    | '/my-trips'
    | '/tk-miles'
    | '/admin/messages'
    | '/api/chat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/check-in'
    | '/destinations'
    | '/flight-status'
    | '/manage-booking'
    | '/my-trips'
    | '/tk-miles'
    | '/admin/messages'
    | '/api/chat'
  id:
    | '__root__'
    | '/'
    | '/check-in'
    | '/destinations'
    | '/flight-status'
    | '/manage-booking'
    | '/my-trips'
    | '/tk-miles'
    | '/admin/messages'
    | '/api/chat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckInRoute: typeof CheckInRoute
  DestinationsRoute: typeof DestinationsRoute
  FlightStatusRoute: typeof FlightStatusRoute
  ManageBookingRoute: typeof ManageBookingRoute
  MyTripsRoute: typeof MyTripsRoute
  TkMilesRoute: typeof TkMilesRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tk-miles': {
      id: '/tk-miles'
      path: '/tk-miles'
      fullPath: '/tk-miles'
      preLoaderRoute: typeof TkMilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-trips': {
      id: '/my-trips'
      path: '/my-trips'
      fullPath: '/my-trips'
      preLoaderRoute: typeof MyTripsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage-booking': {
      id: '/manage-booking'
      path: '/manage-booking'
      fullPath: '/manage-booking'
      preLoaderRoute: typeof ManageBookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flight-status': {
      id: '/flight-status'
      path: '/flight-status'
      fullPath: '/flight-status'
      preLoaderRoute: typeof FlightStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations': {
      id: '/destinations'
      path: '/destinations'
      fullPath: '/destinations'
      preLoaderRoute: typeof DestinationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check-in': {
      id: '/check-in'
      path: '/check-in'
      fullPath: '/check-in'
      preLoaderRoute: typeof CheckInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/admin/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckInRoute: CheckInRoute,
  DestinationsRoute: DestinationsRoute,
  FlightStatusRoute: FlightStatusRoute,
  ManageBookingRoute: ManageBookingRoute,
  MyTripsRoute: MyTripsRoute,
  TkMilesRoute: TkMilesRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
